#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
	sysctl -w net.ipv4.tcp_congestion_control=cubic
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0